### ISSUE TITLE
Migrating to Swift 4

### ISSUE THREAD

**Issue by romanbaitaliuk** [tidwall/SwiftWebSocket#105]
`key = trim(line.substring(to: r.lowerBound))`
`value = trim(line.substring(from: r.upperBound))`

'substring(to:)' is deprecated: Please use String slicing subscript with a 'partial range upto' operator.

Any solutions for swift 4 version?

**Comment by romanbaitaliuk** [comment]
Solution: 

`if let r = line.index(of: ":") {`
     `key = trim(String(line[..<r]))`
     `value = trim(String(line[r...]))`
` }`

**Comment by Sega-Zero** [comment]
@tidwall any ETA on this? #103 looks good

**Comment by tidwall** [comment]
@Sega-Zero I just merged #103. Thanks!

**Comment by Sega-Zero** [comment]
@tidwall, we need a release and CocoaPods update :o)

**Comment by yasuradodo** [comment]
Still not fixed for swift 4
```
key = trim(line.substring(to: r.lowerBound))
value = trim(line.substring(from: r.upperBound)) 
```

**Comment by saroar** [comment]
its dead package lol

**Comment by Sega-Zero** [comment]
it's just hasn't been released. point your podfile directly to git to fetch HEAD
