### ISSUE TITLE
New Version To Support Swift 4

### ISSUE THREAD

**Issue by SwiftExpert** [tidwall/SwiftWebSocket#110]
Hi. my project runs on swift 4 and this version doesnt support it. when are you planning to update it?
![screen shot 2018-01-31 at 10 44 14 am](https://user-images.githubusercontent.com/35992075/35613112-b66048f6-0673-11e8-9f03-5c52c0dfadf1.png)

**Comment by tidwall** [comment]
Hi, The current master branch was updated to Swift 4.0 back in October. Perhaps you are pulling an older version of the library?

**Comment by kerrmarin** [comment]
@tidwall can you publish a new version to CocoaPods with the latest changes?

**Comment by tidwall** [comment]
I hope to have an new CocoaPods version soon. Thanks for your patience.

**Comment by hamedsilver** [comment]
I have this problem too ,  ....

**Comment by tidwall** [comment]
I just pushed v2.7.0 supporting Swift/4 for CocoaPods.
