### ISSUE TITLE
anyone gotten this to work in a playground?

### ISSUE THREAD

**Issue by gaming-hacker** [tidwall/SwiftWebSocket#116]
just including the source file not the framework.

```
Playground execution failed:
error: websocket.playground:1:12: error: use of unresolved identifier 'WebSocket'
  let ws = WebSocket("wss://echo.websocket.org")
```

**Comment by strikerEng** [comment]
It may not work in playground if you don't have the necessary dependencies downloaded which I don't know how to add to your Playground. I was thinking about going this route but I just went ahead and created a project for it. It'll save you a headache.

**Comment by gaming-hacker** [comment]
Thanks, that's what I ended up doing as well.  Sorry just forgot to close this issue.
