### ISSUE TITLE
TLS: Having trouble connecting.

### ISSUE THREAD

**Issue by thbaja** [tidwall/SwiftWebSocket#13]
Modifying your Go test server to serve TLS like this:

``` go
err := http.ListenAndServeTLS(":6789", "ssl/server.crt", "ssl/server.key", nil)
    if err != nil {
        log.Fatal("ListenAndServe: ", err)
    }
```

Connecting with this ur:l `"wss://localhost:6789/echo"`

Will give this error on the server-side, and the client can't connect:
`TLS handshake error from [::1]:58856: tls: first record does not look like a TLS handshake`

As you show in your example, there is no issues in connecting to `"wss://echo.websocket.org"`.

The certificates I'm using are self-signed. Might this be causing the issue?
For reference, the modified server works when using Starscream with `selfSignedSSL` property set to `true`.

**Comment by tidwall** [comment]
Self-signed certs are currently not supported by SwiftWebSocket. But I make it so right away.

**Comment by tidwall** [comment]
I pushed the fix to master. Thanks for your help.

**Comment by thbaja** [comment]
Wow, that was fast. Awesome!
![neil-degrasse-tyson-does-a-happy-dance](https://cloud.githubusercontent.com/assets/4272286/10585775/4f2ae93c-7699-11e5-87a1-3bce9187fa18.gif)
