### ISSUE TITLE
Question: Reconnect.

### ISSUE THREAD

**Issue by thbaja** [tidwall/SwiftWebSocket#14]
If for example app goes to background and goes to foreground, and you would like to reconnect to server, then what would be the best approach?

From what I gather, I need to create a new socket object with new event handlers. Is that correct?

If the above approach is correct, then I would respectfully suggest the following: 
Make it possible to create a WebSocket instance without connecting right away. And then being able to ws.close and ws.open on that same object, and reuse the already added eventhandlers.

With this it will also be possible to add eventhandlers and setup other stuff before you actually try to connect to the server. This would be practical to me at least :-)

**Comment by tidwall** [comment]
The current implementation matches the API and behavior of the Javascript version, which auto connects upon instantiation. For current apps using this library, it would be a breaking change to require an `.open()` call prior to connecting; also it would no longer match the JS version (not a deal-breaker, just a nice-to-have). 

The event object is simply a struct and could easily be copied between objects. For example.

``` swift
let event = ws.event
ws = WebSocket("ws://url")
ws.event = event
```

Could this problem be solved by creating a wrapper class around the WebSocket object? Perhaps the wrapper has a `.open()` method which creates a new WebSocket when called. And it (re)assigns the `.event` struct at the same time.

**Comment by thbaja** [comment]
Thanks for the tip, a wrapper is a reasonable solution.

To avoid breaking changes, you could consider letting  a websocket to be instantiated without a URL.
And if it's created without a url, naturally you would have to set this afterwards, and then you could call .open() on it. I think that would be expected behaviour in that case, it would not be a breaking change and it would offer a bit more flexibility.

But I completely respect it if this is not a path you wish to pursue.

A few suggestions however.

``` swift
// Suggestion 1:
let ws = WebSocket()
ws.url = "ws://url"
ws.open()

// Or perhaps 2:
let ws = WebSocket()
ws.openURL("ws://url")

// 3:
let ws = WebSocket("ws://url",  autoConnect: false)
```

**Comment by tidwall** [comment]
I like suggestion 2. I'm working on it.

**Comment by tidwall** [comment]
The master branch now includes this feature.
