### ISSUE TITLE
Release websocket instances when it hasn't connected yet.

### ISSUE THREAD

**Issue by thbaja** [tidwall/SwiftWebSocket#15]
This is somewhat related to #14, which a solution to might apply here also.

When experimenting with bad network conditions, where a 100% packet loss is enforced, it seems that if I create a new WebSocket that hence can't connect to the server and try to close this instance, then it will be retained, including the event handlers.
At least until the underlying NSURLRequest times out.

Using something along the lines of the below code will give me these results:
If network is connected, I will end up with 1 websocket instance.
If there is 100% packet loss, I will end up with 3 instances.

``` swift
var ws = WebSocket("wss://echo.websocket.org")
func echoTest() {
  ws.close()
  ws = WebSocket("wss://echo.websocket.org")
  ws.close()
  ws = WebSocket("wss://echo.websocket.org")
}
```

**Comment by tidwall** [comment]
Interesting. How long is it taking for the underlying network connection to close in your test?

**Comment by thbaja** [comment]
After approx. 70 seconds on iOS 9 simulator, I will get the following error in ws.event.error handler:
Network(The operation couldn’t be completed. Operation timed out)

Since I'm using your convenience [initializer](https://github.com/tidwall/SwiftWebSocket/blob/03d43a551677a2c1d53e34b07dbb7b45b799b0ed/Source/WebSocket.swift#L576), I guess the default timeout for NSURLRequest  will be used, which is 60 seconds according to [apple docs](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSMutableURLRequest_Class/index.html#//apple_ref/occ/instm/NSMutableURLRequest/setTimeoutInterval:).

Curiously I don't get the timeout when running iOS 8.4 simulator, but the websocket instances are still persisted nonetheless. 

I use Apple's network link conditioner if you should wish to experiment yourself.

**Comment by tidwall** [comment]
Thanks for testing this.

I'm seeing similar results. Though not always exactly the same as yours.

With 100% Loss, sometimes the connection closes after about 5-10 secs, sometimes around 60-70 secs, and sometimes it hangs indefinitely. Mostly it hangs. I would expect the underlying connection to timeout, but it doesn't always.

When I switch the Conditioner to OFF while it's hanging, the connection completes after around 30 seconds or so.

This leads be to believe that SwiftWebSocket is working correctly and there's something going on at a deeper level. Most likely with the Network Link Conditioning tool, or worse the NSStreams (though that would be surprising). 

I'll need to investigate further. I'm hoping that an artificial timeout is not needed. I would prefer relying on NSStream for that.

On a side note, I did notice that the CPU was running 100% while hanging. This is definitely a bug.

**Comment by tidwall** [comment]
I ended up adding an artificial timeout of 30 seconds. It appears that this is how Chrome for Mac solved it for their WebSocket object. If it's good enough for them...  
Also fixed the 100% CPU issue.  Let me know if this doesn't work for you and thanks a bunch for your help.
