### ISSUE TITLE
dead lock in main queue

### ISSUE THREAD

**Issue by rowdyroad** [tidwall/SwiftWebSocket#17]
When I use NSCondition or dispatch_semaphore_wait in main_queue for WebSocket response, I have dead lock.

The problem looks like....

WebSocket.swift:
594:      dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 0), dispatch_get_main_queue()){
595:          manager.add(self)
596:      }

**Comment by tidwall** [comment]
I just pushed a fix to master that should address this problem. Let me know if this didn't help.

On a side note, there's a property of the WebSocket object named `eventQueue` that allows for assigning a custom queue for event handling. Not sure if this applies to your project but thought I'd mention it. I find it useful for long running (or blocking) code.

Thank a bunch for your help.

**Comment by rowdyroad** [comment]
Fixed! Thanks a lot.
Of course I use eventQueue for handling.
