### ISSUE TITLE
iOS9 Ready

### ISSUE THREAD

**Issue by ricardopereira** [tidwall/SwiftWebSocket#18]
Is `SwfitWebSocket` ready for iOS9 and App Transport Security?

**Comment by tidwall** [comment]
Yes for iOS9, and as long as the socket connection starts with "wss://" ATS should work out of the box. What issue are you seeing with ATS?

**Comment by ricardopereira** [comment]
I have a simple test trying to connect to ~~`wss://sandbox-realtime.ably.io:443/?accessToken=Xyer8g.EbFHJcHX214Bs79S4JGrPPgbYV49AtxwOPpp5W1sN7Qq_HMrCLyuPyYN8HuE-k0OG7rSwxYsW684H83qZPukMi3ToF5Y2IHlqpi56nNUqgM-LBElfJyepNAemSPQoIuTWIJA8viR2qYblZROgLOUWAg&client_id=client_string&echo=true&format=json`~~

I'm always getting `error Network(The operation couldn’t be completed. Connection reset by peer)`.

I tested it with [https://chrome.google.com/webstore/detail/simple-websocket-client](https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo?hl=en) and it works.

Can you help me to figure it out, please?

**Comment by tidwall** [comment]
This is a bug. It looks like the issue may be with having both `wss://` and `:443` in the url. 

SwiftWebSocket wasn't negotiating an SSL connection when a port is specified. I pushed a change to the dev branch which should allow for both wss and 443 in the url. 

Please let me know if this fixes the problem on your side.

**Comment by ricardopereira** [comment]
Yes, with `dev` branch it is working.

**Comment by ricardopereira** [comment]
One more thing, why don't you have support for Objective-C?

I noticed that `SwiftWebSocket` does not use delegate, right?
One delegate with `@objc` attribute is enough.

**Comment by tidwall** [comment]
Glad the fixed worked for you. 

Regarding ObjC. I personally stopped working with ObjC earlier this year, and I'm a bit rusty with the interop rules. But I'm not totally opposed to adding support if there's a demand for it. Feel free to send a pull request my way.

Thanks a bunch for your help.

**Comment by ricardopereira** [comment]
Well, didn't know that `WebSocket` is a `Hashable` 😶
`Hashable` is a swift protocol and is invalid for Objective-C.
Need to think about it.

**Comment by tidwall** [comment]
I'm not sure that Hashable is required for the `WebSocket` class. There's an `InnerWebSocket` that must be Hashable because the Manager stores them in a Set, but the outer WebSocket is just a wrapper. Perhaps the Hashable can be removed.
