### ISSUE TITLE
Reconnect sample doesn't actually reconnect.

### ISSUE THREAD

**Issue by angerman** [tidwall/SwiftWebSocket#22]
assuming the following code to reconnect on close:

```
let ws = WebSocket()
ws.event.close = { _ in
    ws.open()                 // reopen the socket to the previous url
}
ws.open("ws://url") // call with url
```

The inner `ws.open()` will return immediately as the internal `opened` flag is still `true`.

My current workaround is, calling close prior to calling open.

```
let ws = WebSocket()
ws.event.close = { _ in
    ws.close()
    ws.open()                 // reopen the socket to the previous url
}
ws.open("ws://url") // call with url
```

Is this the expected behavior?

**Comment by tidwall** [comment]
This was not the intended behavior. I made a fix to address this issue. Thanks
