### ISSUE TITLE
Header field name keys case-sensitivity

### ISSUE THREAD

**Issue by eeekari** [tidwall/SwiftWebSocket#26]
Hi - While enabling compression, I noticed that the keys "Sec-Websocket-SubProtocol" and "Sec-Websocket-Extensions" are switched on without testing the case of the string.

I couldn't find any reference in the RFC protocol anything that was overly clear regarding case sensitivity in the header string, but it does appear that the NSURLRequestClass Reference indicates these field names should be case-insensitive.

In the below snippet

``` swift
func readResponse() throws {
....
    switch key {
        case ("Sec-WebSocket-SubProtocol"):
            privateSubProtocol = value
        case ("Sec-WebSocket-Extensions"):
            let parts = value.componentsSeparatedByString(";")
...
}
```

I think this should probably be sanitized either:

``` swift
func readResponse() throws {
....
    if (key.caseInsensitiveCompare("Sec-WebSocket-SubProtocol") == .OrderedSame) {
        privateSubProtocol = value
    } else if (key.caseInsensitiveCompare("Sec-WebSocket-Extensions") == .OrderedSame) {
        let parts = value.componentsSeparatedByString(";")
...
}

```

or:

``` swift

func readResponse() throws {
....
    switch key.lowercaseString {
        case ("Sec-WebSocket-SubProtocol").lowercaseString:
            privateSubProtocol = value
        case ("Sec-WebSocket-Extensions").lowercaseString:
            let parts = value.componentsSeparatedByString(";")

...
}
```

I'm unsure if there are other areas which may require a similar update, just raising to your attention.

**Comment by tidwall** [comment]
Thanks for the tip. I agree with your approach.
