### ISSUE TITLE
Swift 2.2 - Unknown attribute asmname

### ISSUE THREAD

**Issue by macteo** [tidwall/SwiftWebSocket#28]
It seems that on Xcode 7.3b2 and the included Swift 2.2 beta version, the keyword `@asmname` has been removed so all those methods are generating errors and preventing the build.

``` swift
@asmname("zlibVersion") private func zlibVersion() -> COpaquePointer
@asmname("deflateInit2_") private func deflateInit2(strm : UnsafeMutablePointer<Void>, level : CInt, method : CInt, windowBits : CInt, memLevel : CInt, strategy : CInt, version : COpaquePointer, stream_size : CInt) -> CInt
@asmname("deflateInit_") private func deflateInit(strm : UnsafeMutablePointer<Void>, level : CInt, version : COpaquePointer, stream_size : CInt) -> CInt
@asmname("deflateEnd") private func deflateEnd(strm : UnsafeMutablePointer<Void>) -> CInt
@asmname("deflate") private func deflate(strm : UnsafeMutablePointer<Void>, flush : CInt) -> CInt
@asmname("inflateInit2_") private func inflateInit2(strm : UnsafeMutablePointer<Void>, windowBits : CInt, version : COpaquePointer, stream_size : CInt) -> CInt
@asmname("inflateInit_") private func inflateInit(strm : UnsafeMutablePointer<Void>, version : COpaquePointer, stream_size : CInt) -> CInt
@asmname("inflate") private func inflateG(strm : UnsafeMutablePointer<Void>, flush : CInt) -> CInt
@asmname("inflateEnd") private func inflateEndG(strm : UnsafeMutablePointer<Void>) -> CInt
```

**Comment by tidwall** [comment]
Swift 2.2 abruptly removed the `@asmname` attribute in favor of `@_silgen_name`. 

There's a branch named `swift/2.2` for this project that addresses this issue. As soon as Xcode 7.3 goes live I will merge with the master branch.

**Comment by macteo** [comment]
Sorry, didn't saw it.
Thanks for your patience.

**Comment by tidwall** [comment]
Actually the branch has been sitting on my laptop for a couple weeks. I didn't push it to Github until you opened this issue. 

Also I'm going to keep this issue open until 7.3 is final... in case others might run into the same problem.

Thanks for your help!

**Comment by macteo** [comment]
Thanks for your work!

**Comment by Skogetroll** [comment]
Just a reminder: [Xcode 7.3 was released](https://developer.apple.com/xcode/download/). It's time to merge `swift/2.2` with `master`.

**Comment by GaborWnuk** [comment]
+1, currently can't build on Xcode 7.3 as it went out of beta :)

**Comment by LukasGram** [comment]
+1

**Comment by macteo** [comment]
+1

**Comment by jaimeazevedo** [comment]
+1

**Comment by tidwall** [comment]
Just pushed an update. There is also a **swift/2.0** branch for projects that are not Xcode 7.3 ready.

Please let me know if anyone runs into trouble.

Thanks for your patience.

**Comment by jaimeazevedo** [comment]
Thank you very much! :)

**Comment by macteo** [comment]
Thanks!

**Comment by ricardopereira** [comment]
No backward compatibility? 😞

You could use the new compiler directive:

``` swift
#if swift(>=2.2)
print("Running Swift 2.2 or later")
#else
print("Running Swift 2.0 or earlier")
#endif
```

v2.6 could be used on Xcode 7.2 and 7.3.
WDYT?

**Comment by tidwall** [comment]
@ricardopereira I don't think this will work. The '#if swift` directive was introduced in the swift 2.2 compiler. There's no way that I know of to detect the version of the Swift compiler prior to 2.2.

I'm still looking for a work around. It seems that the switch from `@asmname` to `@_silgen_name` totally broke backwards compatibility for any project needing that functionality.

I pushed a `swift/2.0` branch to help remedy the problem. I know it's not ideal, but it's the only option I'm aware of. 

If you have any ideas please let me know. Sorry for the inconvenience. :(

**Comment by ricardopereira** [comment]
@tidwall Oh, I see. You right. Damn it 😫.
I think the best is to have two different branches like you have then.
Thanks
