### ISSUE TITLE
abnormal timeout or missing something?

### ISSUE THREAD

**Issue by Kowaio** [tidwall/SwiftWebSocket#30]
Hello guys,

First of all, thanks a lot for your work, this lib is amazing. I'm contacting you today because I've encountered some timeout issues but I don't know if it's normal or if I'm missing something.

I create the socket like so:
`socket = WebSocket(url: url)
socket?.delegate = self
socket?.open()`

When receiving `webSocketOpen`, I send some data to authenticate my websocket but after 30 seconds, the websocket is closing all by itself. 
Do I need to do something to keep it alive? Like ping it every 30s or so? I need to keep it alive in case the server needs to send me text message at any moment (but that can be way longer than 30 seconds after the socket being created).

Thanks a lot for your help guys.

Best regards,

**Comment by tidwall** [comment]
I'm guessing that having both a constructor with a url in it and calling `.open()` is the culprit.

If you are specifying a url in the `WebSocket(url)` constructor, then you should not call `.open()`. 
Also, unless you writing your code in Objective-C, then you should not be using the `.delegate` property. I recommend that you use the `.event` property instead.

You code should look something like this...

``` swift
var socket = WebSocket(url)
socket.event.message = { ... }
```

Checkout the example shown on the [README](https://github.com/tidwall/SwiftWebSocket/blob/master/README.md)

Let me know if this doesn't help and thanks for supporting the project!

**Comment by Kowaio** [comment]
Hi again,

Thanks a lot for your quick replay.

I removed the `delegate` property and change my `init` method like so:

`class SocketController: NSObject {
    var socket: WebSocket?

```
init(url: NSURL) {
    super.init()
    socket = WebSocket(url: url)
    let auth : ()->() = {
        if let data = self.authenticate() {
            self.socket?.send(data)
        }
    }
    socket?.event.open = {
        auth()
    }
    socket?.event.close = { code, reason, clean in
        log.verbose("webSocketClose code=\(code), reason=\(reason)")
    }
    socket?.event.error = { error in
        log.verbose("webSocketError \(error)")
    }
    socket?.event.message = { message in
        if let text = message as? String {
            log.verbose("text \(text)")
        }
        else {
            log.verbose("data")
        }
    }
}
```

The method `self.authenticate()` just send some data to the server, which gives me a correct text response in the `event.message`.

However, after a time (30 seconds approximately), I receive a `webSocketClose` log message with `code=0.` The only way I found for the socket to not close is for me to ping it every 20 seconds or so, but that's weird, right?

Thanks again for your time.

**Comment by tidwall** [comment]
It sounds like the server is expecting messages from the client within that 20 second window. This could be for any number of reasons, but most likely for the server to know that the connection is still alive.

There are no rules in the WebSocket specification defining keep-alives, but it's actually pretty common for socket servers to require a ping/pong every few seconds or so. Typically it's the server that sends a ping to the client and the client will respond with a pong message, which SwiftWebSocket does in the background. But in the case of your server, it sounds like the client must send the ping. 

I recommend setting up a timer and pinging every 5 seconds or so.
