### ISSUE TITLE
Receive buffer grows in size

### ISSUE THREAD

**Issue by palmerc** [tidwall/SwiftWebSocket#35]
When receiving a high-speed stream of data over the WebSocket the receive buffer keeps realloc'ing an ever larger buffer because the message events cannot be dealt with fast enough. It would be useful if you could instruct the WebSocket to pop the last message and discard all buffered messages or set a maximum number of buffered messages.

**Comment by tidwall** [comment]
SwiftWebSocket doesn't maintain a stack of messages. It reads one message at a time from the underlying `NSInputStream`. When a message is received it calls the `event.message` event handler and blocks until the handler is complete. Then continues to the next message. The old message state is discarded.

The underlying `NSInputStream` maintains it's own buffer and it will fill this buffer when it receives new data from the server. This buffer is at a lower level than SwiftWebSocket and it's memory is not something that can be controlled by the client library.

If messages are being received faster than the your `event.message` can handle them, then then `NSInputStream` buffer will likely grow without limit.

The only way around this is for the `event.message` to do less work. 

How many messages per second are you handling? And about what is the average size of each message?

**Comment by palmerc** [comment]
The line with realloc in stepBuffers() is the issue. And the buffer eventually reallocs until about 1GB when the app dies. I'm receiving roughly 25, 280KB frames a second.

**Comment by tidwall** [comment]
Thanks @palmerc. That's very helpful. Sounds like this is an issue with the library. Let me dive into the code and find out what's going on.

**Comment by tidwall** [comment]
I was able to reproduce the error with your information. The buffer still grows depending on tcp fragmentation, but it stays within a reasonable size. Please let me know if this fixes the problem in your app. 
Thanks a ton for your help!
