### ISSUE TITLE
2.6 Doesn't Build with Carthage

### ISSUE THREAD

**Issue by siegesmund** [tidwall/SwiftWebSocket#37]
GIves the laconic error message: 

```
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal arm64 /Users/peter/Dropbox/Development/Programming/Swift/SwiftDDP/Carthage/Checkouts/SwiftWebSocket/Source/WebSocket.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal arm64 /Users/peter/Dropbox/Development/Programming/Swift/SwiftDDP/Carthage/Checkouts/SwiftWebSocket/Source/WebSocket.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

```

**Comment by tidwall** [comment]
Hi @siegesmund, thanks for reporting this error.

Carthage isn't providing much details to go on. Did it happen to output the command that it uses to compile, and are there any additional output such as line numbers? Also what versions of Carthage and Swift are you using?

I would like to reproduce this issue if possible.

**Comment by siegesmund** [comment]
swift version:

```
Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
Target: x86_64-apple-macosx10.9
```

carthage version: 0.15.1

Regarding the compile command, I thought that was what I included above. If not, what does that look like?

Also, did you push 0.2.6 to Cocoapods? I'm only seeing 0.2.5 and this is what loads by default...

**Comment by tidwall** [comment]
You did include the command in the original message, Sorry. Thanks for the pointing that out. 

I did push [SwiftWebSocket 2.6.0](https://cocoapods.org/pods/SwiftWebsocket) to Cocoapods yesterday.

**Comment by tidwall** [comment]
I tested and wasn't able to reproduce this problem. I have Carthage `0.15.2` installed and Swift `2.2`.

I place a basic Cartfile with the contents...

```
github "ReactiveCocoa/ReactiveCocoa"
github "tidwall/SwiftWebSocket"
```

...into an empty directory. Then ran `carthage update`. 

The console output was:

``` bash
*** Fetching SwiftWebSocket
*** Fetching ReactiveCocoa
*** Fetching Result
*** Downloading Result.framework binary at "1.0.2: A Swift Result"
*** Downloading ReactiveCocoa.framework binary at "v4.0.1"
*** Checking out SwiftWebSocket at "2.6.0"
*** xcodebuild output can be found in /var/folders/vd/jr9h6jyj1n34s5nsphy6y88m0000gn/T/carthage-xcodebuild.U38j55.log
*** Building scheme "SwiftWebSocket-OSX" in SwiftWebSocket.xcodeproj
*** Building scheme "SwiftWebSocket-tvOS" in SwiftWebSocket.xcodeproj
*** Building scheme "SwiftWebSocket-iOS" in SwiftWebSocket.xcodeproj
```

Everything seemed to build correctly. I there anything else I should do to verify?

**Comment by siegesmund** [comment]
I upgraded to Carthage 15.2, and I removed the version constraint on SwiftWebSocket to match your file. The outcome is the same.

In the meantime, I've just removed Carthage as a recommended install method in the library that depends on SwiftWebSocket...

**Comment by tidwall** [comment]
Good to know. Which library are you using that depends on SwiftWebSocket?

**Comment by siegesmund** [comment]
Still trying to get it to build. Seems like this is probably an edge case, so...

The library is [SwiftDDP](https://github.com/siegesmund/SwiftDDP). SwiftWebSocket is really it's backbone. Thanks for publishing it!

**Comment by siegesmund** [comment]
I cleaned out the project directory and started from scratch with Carthage, and on the second attempt, it builds. It seems like this is probably not a SwiftWebSocket issue, but something related either to my environment or to Carthage itself.

**Comment by tidwall** [comment]
@siegesmund very good to know. Thanks much!
