### ISSUE TITLE
IPV6 support ?

### ISSUE THREAD

**Issue by mozinator** [tidwall/SwiftWebSocket#41]
Apple announced that new iOS apps should have ipv6 support. [1]
Does SwiftWebSocket support ipv6 ?

[1] https://developer.apple.com/news/?id=05042016a

**Comment by tidwall** [comment]
Yes. SwiftWebSocket uses the IPV6 ready function [CFStreamCreatePairWithSocketToHost](https://developer.apple.com/library/ios/documentation/CoreFoundation/Reference/CFStreamConstants/#//apple_ref/c/func/CFStreamCreatePairWithSocketToHost) to establish connections.
