### ISSUE TITLE
Feature: Can add helper wrapper to this socket

### ISSUE THREAD

**Issue by pinkfloyda** [tidwall/SwiftWebSocket#46]
Sometimes, we want to maintain one SwiftWebSocket instance to connect to one URL only. So when current socket opening, if the user wants to reopen it (e.g. switch to connect a new URL), he has to close it first and then in the close event to reopen it. Such operations can have errors and better to implement a wrapper for this. Similar for operations like retry code logic in fail.

**Comment by tidwall** [comment]
@pinkfloyda thanks for the feature suggestion. There's some [code in the Readme](https://github.com/tidwall/SwiftWebSocket#reuse-and-delaying-websocket-connections) that shows how to reuse the same connection. Would this address your concern?
