### ISSUE TITLE
Migration to Swift 3.0

### ISSUE THREAD

**Issue by KMicrosystems** [tidwall/SwiftWebSocket#47]
Hello,
Wondering if you plan to migrate to Swift 3.0 soon and if so, when? Thanks!

**Comment by maxsokolov** [comment]
+1

Would be great to know.

**Comment by tidwall** [comment]
Absolutely. Migration to Swift 3 is currently in the works. You will soon see a separate `swift/3.0` branch. When Xcode 8 goes GM I will merge `swift/3.0` with the master branch. I can't say exactly when it will be ready, but I expect days not weeks.

**Comment by tidwall** [comment]
I pushed the branch moments ago. There's still Autobahn testing to complete, but the syntax and basic checks pass. Please let me know of any issues you run into. Thanks!
