### ISSUE TITLE
Cannot receive pong with event handler

### ISSUE THREAD

**Issue by css459** [tidwall/SwiftWebSocket#48]
I've implemented my pong event handler like so

```
      self.socket.event.pong {
            print("PONG")
            self.dm.pongReceived = true
        }
```

except whenever I send a pong to this swift client, `PONG` is never printed to the console and thus, the event handler is never called. Is there anything I can do to fix this? I'm fairly sure my server is sending pongs correctly.

**Comment by tidwall** [comment]
Looks like you are missing some syntax. Try this:

``` swift
self.socket.event.pong = { _ in
    print("PONG")
    self.dm.pongReceived = true
}
```

**Comment by tidwall** [comment]
I'm closing this issue for now. Please feel free to reopen if are still running into problems. Thanks!
