### ISSUE TITLE
Cannot use my own origin for websocket

### ISSUE THREAD

**Issue by maxsokolov** [tidwall/SwiftWebSocket#49]
Hi @tidwall 

Thanks a lot for such a great library. But I have an issue.

I want to use my own custom origin for connection request like this:

```
let mutableRequest = NSMutableURLRequest(URL: "my socket url")
mutableRequest.addValue("my value", forHTTPHeaderField: "cookie")
mutableRequest.addValue("my value", forHTTPHeaderField: "origin")

socket.open(request: mutableRequest)
```

It's important for test purpose. We have dev and production servers.

But as I can see in private `InnerWebSocket` class:

`req.setValue(req.URL!.absoluteString, forHTTPHeaderField: "Origin")`

you always use Origin from the request that I've provided to make a connection.

So in that case we just can't organise our test environment.
It would be great if you add some `if` statement for the Origin http field, if there is something that user provided, otherwise set Origin from the request url.

Thanks a lot!

**Comment by tidwall** [comment]
Thanks for reporting this. I agree that it's wrong for the library to squash the custom Origin header. I like your suggestion of adding an `if` statement to check the header before automatically setting it. 

I'll work on a fix and post it asap.

**Comment by maxsokolov** [comment]
@tidwall thank you! May I expect a CocoaPod release soon?

**Comment by tidwall** [comment]
@maxsokolov You're welcome! I just posted a new CocoaPod release. Thanks a bunch for your help.

**Comment by maxsokolov** [comment]
@tidwall looks like v2.6.3 has not been pushed to CocoaPods, I can't update for this version.

Have you pushed it with command?
`pod trunk push SwiftWebSocket.podspec`

**Comment by tidwall** [comment]
@maxsokolov Shoot! I forgot to push. I just did it for real this time. Thanks for reminding me.

**Comment by maxsokolov** [comment]
Wow) that was fast! Thank you!

**Comment by tidwall** [comment]
You're welcome. Let me know if you have any problems with it. And thanks for your help.
