### ISSUE TITLE
OSX Version

### ISSUE THREAD

**Issue by ricardopereira** [tidwall/SwiftWebSocket#5]
I added OSX target for version 0.1.18 (Swift 1.2):
- https://github.com/ricardopereira/SwiftWebSocket/tree/rp-osx-v0.1.18

Do you want a PR?
If so, create a branch for that fix.

OSX target it's missing for the current version.

**Comment by tidwall** [comment]
Perfect. I just merged in your update to v0.1.20. Should be Cocoapod compat.

**Comment by tidwall** [comment]
Let me know if the merge worked for you. I did a reverse merge into a new branch and made some minor updates and tagged it. Apparently this doesn't count in the Github world as adding you to the Contributor count. I should have just let you create the PR....

**Comment by ricardopereira** [comment]
Oh, no problem :+1:
You can delete the branch. I use the tagged one with carthage.
Thank you.
