### ISSUE TITLE
provide JSON data with socket init

### ISSUE THREAD

**Issue by antons81** [tidwall/SwiftWebSocket#52]
Hi,

Hi I could provide JSON data parameters to server with its initialization?
 like socket.IO framework

**Comment by tidwall** [comment]
Hi Anton,

You should be able to send any type of data to the server, including JSON. Though, I'm not sure what you mean by "with its initialization". 

Socket.IO is a higher level protocol that runs on top of websockets and provides a more specified set of functionality.

I hope this information helps and thanks for your interest in SwiftWebSocket.
