### ISSUE TITLE
Reconnect timeout

### ISSUE THREAD

**Issue by jimmyshiau** [tidwall/SwiftWebSocket#53]
When I try to turn off wifi and turn on
I will start a timer to detect network connection and try to reconnect socket with `socket.open()`

sometimes works but sometimes I got timeout after long time
but I try to use browser websocket to connect my server it works fine

any idea?

**Comment by tidwall** [comment]
Hi Jimmy, 

I haven't heard of this problem before. Is it easy to reproduce?

If it is a bug, I would like to get it fixed asap. Do you have some code that might cause it to happen?

Thanks.

**Comment by jimmyshiau** [comment]
OK I will try to test with a simple sample

**Comment by jimmyshiau** [comment]
Hi 

It  seems network issue..
when I turn off wifi then reopen it

sometimes it will timeout  when connect to server 
even I using NSMutableURLRequest to access server

I think it is network issue, you can close this issue, thanks

**Comment by fukemy** [comment]
nope, i sure the socket DOES NOT RECONNECT AUTOMATICALLY, and it's does not get disconnect event, so user think it's still running, but every message send => failed until it's got disconnected after timeout
