### ISSUE TITLE
Use [weak self] instead of [unowned self]

### ISSUE THREAD

**Issue by makhmutov** [tidwall/SwiftWebSocket#55]
App crashes:
![screen shot 2016-08-15 at 12 18 52](https://cloud.githubusercontent.com/assets/2269658/17658117/959e03d2-62e2-11e6-862a-791a1b9e6f8a.png)

I'm recreating new WebSocket instance in :`func webSocketError(error: NSError)`or `func webSocketClose(code: Int, reason: String, wasClean: Bool)`.

Looks like, there is no guarantee that `WebSocket` will exist, when closure will be called.

Version: 2.6.1.

I will let you know if I catch same error on 2.6.3

**Comment by tidwall** [comment]
Thanks for catching this error. I just pushed an update to the master branch.
