### ISSUE TITLE
Can it support IPv6?

### ISSUE THREAD

**Issue by tannt275** [tidwall/SwiftWebSocket#60]
I want to know can it support IPv6 for implement my app. Thanks

**Comment by tidwall** [comment]
Yes. IPv6 is supported.

**Comment by tannt275** [comment]
Thanks for support. And i have another question. Can this library connect TCP with a server (in my case is netty https://github.com/netty/netty).

**Comment by tidwall** [comment]
It should work. I don't have hands on experience with netty, but as I understand it works over Websockets. Both netty and SwiftWebSocket work over TCP.

**Comment by tannt275** [comment]
Okie thanks @tidwall
