### ISSUE TITLE
Can it support background mode?

### ISSUE THREAD

**Issue by NikitaCh** [tidwall/SwiftWebSocket#61]
Hi, can this library keep connection alive when user put an application on background?

Thanks,
Nikita

**Comment by tidwall** [comment]
Yes. As long as your application has permission to use the network in the background, such as a VoIP app.

https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html.

**Comment by NikitaCh** [comment]
I've enabled all background modes.
Also i've set service of WebSocket instance to .Background. 
But as soon as i get to background mode, after about 30 seconds websocket closes the connection.

Thanks,
Nikita.

**Comment by tidwall** [comment]
It's sounds like iOS is still killing the connection when your app goes to the background. SwiftWebSocket does supports long running connections, so there must be a setting that is being missed.  You may want to ask on https://forums.developer.apple.com

**Comment by NikitaCh** [comment]
Thanks,

I've found post by link: https://forums.developer.apple.com/thread/35065?q=Websocket
Seems like iOS will kill it anyway, it can just give some seconds to finish your networking...

Hope someone there knows how to workaround it somehow.

As this is not your lib problem, i'm closing the issue. Thank you for quick responses.

Thanks,
Nikita.

**Comment by tidwall** [comment]
You're welcome and good luck.
