### ISSUE TITLE
socket header

### ISSUE THREAD

**Issue by eleneakhvlediani** [tidwall/SwiftWebSocket#62]
socket?.event.header = { message in
}

I was reading socket header with following code, but in new version socket event doesn't have header field. So what is the new way to read header?

**Comment by tidwall** [comment]
I don't recall there being an event.header. Which version did this event exist? Right now there's no event that reads the HTTP header.

Current the only valid events are:
open,close,error,message,pong,end.

**Comment by eleneakhvlediani** [comment]
@tidwall so there is no way to read header when connection is established?

I also have another problem when opening socket, I get protocol error 1002 after opening. Do you what can be the reason ?

**Comment by tidwall** [comment]
There is currently no way to read the HTTP header.

1002 happens when there's an problem with websocket data from the server.  Perhaps the socket that you are connecting to is a different protocol than a WebSocket?

**Comment by eleneakhvlediani** [comment]
@tidwall sorry I found that it was added by me

**Comment by tidwall** [comment]
No worries. :)
