### ISSUE TITLE
Unable to find a specification for 'SwiftWebSocket' for Cocoapods

### ISSUE THREAD

**Issue by InnaLMC** [tidwall/SwiftWebSocket#66]
Hi, I tried to install the lat version, but Cocoapods gave me an error: [!] Unable to find a specification for 'SwiftWebSocket'.
I wrote in pod file this variants:

pod 'SwiftWebSocket', :git => 'https://github.com/tidwall/SwiftWebSocket.git', :branch => 'swift/3.0'

pod 'SwiftWebSocket', :git => 'https://github.com/tidwall/SwiftWebSocket.git', :branch => 'master'

pod 'SwiftWebSocket', :git => 'https://github.com/tidwall/SwiftWebSocket.git'

but the error was the same.
Only this variant allowed me to install pod:

pod 'SwiftWebSocket'

but it's deprecated code.

Could you please restore podspec?

**Comment by tidwall** [comment]
Hi InnaLMC, 

Thanks for letting me know. I restored the podspec back to the project. Please let me know if this works better for you.

**Comment by InnaLMC** [comment]
I guess issue should be closed

**Comment by tidwall** [comment]
Were you able to install the project with the provide podspec?
