### ISSUE TITLE
Pod version 2.6.3 doesn't have weak/unowned reference fix

### ISSUE THREAD

**Issue by maxsokolov** [tidwall/SwiftWebSocket#67]
Hey @tidwall 

I'm using 2.6.3 version of the library via Cocoapods. I can see that master branch and swift/2.2 branch have this fix with weak/unowned reference. But the release with tag 2.6.3 still has unowned in the source.

You may download https://github.com/tidwall/SwiftWebSocket/releases/tag/2.6.3 directly and check that.

**Comment by maxsokolov** [comment]
I guess you could just delete current 2.6.3 tag/release and create it again.

**Comment by tidwall** [comment]
Darn it! Thanks for reporting. I'll work on a fix asap. Does pointing to the swift/2.2 branch work in the meantime?

**Comment by maxsokolov** [comment]
Yep, I hardcoded swift/2.2 branch in my podfile.

**Comment by tidwall** [comment]
OK.  I just pushed CocoaPods release with the unowned bug fix. Version 2.6.4 is now available and seems to be working. Let me know if this does not work for you and thanks a ton for you help.

**Comment by maxsokolov** [comment]
Everything is ok now. Thanks a lot!
