### ISSUE TITLE
question about the eventQueue - dispatch_queue_t is unavailable in SWIFT

### ISSUE THREAD

**Issue by csmobile** [tidwall/SwiftWebSocket#69]
Hi, 

I am getting an error dispatch_queue_t is unavailable in SWIFT in the current build.  Is there un update by any chance?

**Comment by csmobile** [comment]
I see that some are recommending to use DispatchQueue instead... would this work with the existing build?

**Comment by tidwall** [comment]
This [change](https://github.com/tidwall/SwiftWebSocket/blob/830a81539db151c336e7bbd15fd32a0b18e7fdd1/Source/WebSocket.swift#L533) was made when we migrated to Swift 3. Perhaps you are using an older build?
