### ISSUE TITLE
Version tag with Swift 3 support?

### ISSUE THREAD

**Issue by programmarchy** [tidwall/SwiftWebSocket#70]
Based on the commit log, it looks like tag 2.6.4 should be on commit 3a77b8925dad45528dfea6e9ea042c6c5b9382ec, but it's actually on 6c15a4cb4c9a974c57a45f2c3f37274469491025.

This is a little confusing, because tag 2.6.4 seems to indicate supports swift 3, but really one needs to checkout the head of master to get Swift 3 -- there's no version tag to reference yet.

**Comment by tidwall** [comment]
Thanks for alerting me to this. It does look a little wonky. I just pushed a new version 2.6.5 that is now even with swift/3.0 and master. I hope this cleans it up a bit.

**Comment by programmarchy** [comment]
Thank you!

**Comment by tidwall** [comment]
You're welcome and thanks again for reporting the issue.
