### ISSUE TITLE
Subscribing to room

### ISSUE THREAD

**Issue by dizialina** [tidwall/SwiftWebSocket#72]
Hi! I have server with rooms to chat. Full url is ws://93.171.XXX.XX:8080/conversation_realtime/sportspace581a1541590b21.14581077".   
But I have to connect to this by 2 steps:
1) connect to "ws://93.171.XXX.XX:8080"   
2) subscribe to room "conversation_realtime/sportspace581a1541590b21.14581077"

In JS it  looks like:
```
var _WS_URI = "ws://93.171.242.80:8080";
var webSocket = WS.connect(_WS_URI);

webSocket.on("socket/connect", function(session){
session.subscribe("conversation_realtime/sportspace581a1541590b21.14581077", function(uri, payload){
                    console.log(payload.message.text);
}
}
```
Can I realize it in swift in SwiftWebSocket library? Can't find subscribing to rooms.

**Comment by tidwall** [comment]
It's possible that SwiftWebSocket will work for you, but I don't recognize the `WS.connect()` function. Which socket library are you using in Javascript? Socket.IO maybe?

**Comment by dizialina** [comment]
My web developers said that it is "goswebsocket" library, and this library uses "Ratchet\/0.3.3"

**Comment by tidwall** [comment]
It appears that the Javascript goswebsocket client library is a wrapper around the standard `WebSocket` object, and that it adds a simple PubSub API to browser apps. 

While it's possible to create a websocket connection and send/recv messages with the Ratchet server using SwiftWebSocket, the special PubSub APIs may not be available without adding a goswebsocket compaible wrapper around SwiftWebSocket.

I recommend that you ping the [GeniusesOfSymfony/WebSocketBundle](https://github.com/GeniusesOfSymfony/WebSocketBundle) developers to see if they know of any iOS libraries that support their APIs.

**Comment by dizialina** [comment]
Ok, thank you for help

**Comment by tidwall** [comment]
You're welcome and best luck with your project.
