### ISSUE TITLE
swift 3 demo

### ISSUE THREAD

**Issue by amitg02** [tidwall/SwiftWebSocket#73]
How to use this code in my project in xocde 8 swift3

**Comment by tidwall** [comment]
Hi @amitg02, There's an [example](https://github.com/tidwall/SwiftWebSocket#example) in the README.

**Comment by amitg02** [comment]
i want to know step for adding library in our project. @tidwall

**Comment by tidwall** [comment]
You can use [CocoaPods](https://cocoapods.org/pods/SwiftWebSocket), [Carthage](https://github.com/Carthage/Carthage), or copy the [Websocket.swift](https://github.com/tidwall/SwiftWebSocket/blob/master/Source/WebSocket.swift) file directly to your project.

**Comment by tidwall** [comment]
Hi @amitg02 ,

I'm closing this issue for now, but please feel free to reopen  if you have any further questions around this topic. 
 
Thanks for interest in SwifWebSocket
