### ISSUE TITLE
link errors when using swift package manager

### ISSUE THREAD

**Issue by ghost** [tidwall/SwiftWebSocket#74]
<img width="242" alt="screen shot 2016-11-17 at 12 45 16 am" src="https://cloud.githubusercontent.com/assets/2278174/20356506/a9822b96-ac5f-11e6-8e11-5a626b313a25.png">

**Comment by tidwall** [comment]
Hi @JayZhao,

Sorry about the delayed response. Were you able to resolve this issue?

**Comment by utdrmac** [comment]
Same issues here. Not using any package managers. I simply downloaded WebSocket.swift and added to my project. Xcode 8.1 / macOS 10.12.1

Xcode -> New project -> cocoa application -> {name: tester, language: Swift, no other checkboxes checked} -> saved project to desktop. Add files -> WebSocket.swift {copy if necessary} -> Build. Errors as above.

**Comment by utdrmac** [comment]
[Build target tester_2016-12-07T11-09-17.txt](https://github.com/tidwall/SwiftWebSocket/files/637261/Build.target.tester_2016-12-07T11-09-17.txt)

**Comment by tidwall** [comment]
Hi Matthew,

To manually install you also need to add libz.dylib.

1) Copy the SwiftWebSocket/WebSocket.swift file into your project.
2) Add the libz.dylib library. Project -> Target -> Build Phases -> Link Binary With Libraries

**Comment by utdrmac** [comment]
Thanks. That allowed it to compile. Will probably fix @JayZhao 's issue too. Can probably close this.

**Comment by smhk** [comment]
Just for anyone googling here, it's nowadays ".tbd" otherwise all the same.
![tbd](https://user-images.githubusercontent.com/3938526/163724455-282bcebe-a109-4dc6-a50a-9d0c6744345a.jpg)
