### ISSUE TITLE
The operation couldn’t be completed. (SwiftWebSocket.WebSocketError error 4.)

### ISSUE THREAD

**Issue by qadir-genetech** [tidwall/SwiftWebSocket#80]
I am trying to connect to my loxone mini server via socket using your library with the following code. 

```
           let websocketScheme = "ws"
            let host = "192.168.14.247"
            let port: NSNumber = 8888
            
            let components = NSURLComponents()
            components.scheme = websocketScheme
            components.host = host
            components.port = port
            components.path = "/"
            
            print("URL \(components.url)")
            
            var request = URLRequest(url: components.url!)

            request.setValue("Upgrade", forHTTPHeaderField: "WebSocket")
            request.setValue("Connection", forHTTPHeaderField: "Upgrade")
            request.setValue("Sec-WebSocket-Protocol", forHTTPHeaderField: hash as String)  
            
            socket = WebSocket(request: request as URLRequest)
            
            socket?.delegate = self
            socket?.open()

```

but I am keep getting error

`The operation couldn’t be completed. (SwiftWebSocket.WebSocketError error 4.)`

what could be the issue? any directions/pointers please

**Comment by tidwall** [comment]
SwiftWebSocket handles all of the boilerplate http headers, so you typically don't need all of the `request.setValue()` stuff. Also the `socket?.open()` isn't usually needed.

Perhaps try something like:
```
socket = WebSocket("ws://192.168.14.247:8888")
socket?.delegate = self
```

**Comment by qadir-genetech** [comment]
nope. tried as above. but got same issue
`The operation couldn’t be completed. (SwiftWebSocket.WebSocketError error 4.)`

**Comment by olivier38070** [comment]
same on my side.

**Comment by qadir-genetech** [comment]
@olivier38070 are you trying to connect the loxone miniserver via socket?

**Comment by olivier38070** [comment]
no, I try to connect to perfect swift web socket server. this server works "fine", when I do websocket in javascript (inside an html page).

**Comment by olivier38070** [comment]
ok solved : 
I had to add the sub protocol, and check on server side if I was filtergin with the proper protocol
and I had to instanciate the WebSocket object in a global variable, instead on in a func .

**Comment by DanielSmith1239** [comment]
I'm running into the error 4 issue now.

**Comment by pablogeek** [comment]
I'm also having this error....

**Comment by VikranthKumar05** [comment]
let ws = WebSocket("wss://myteambit.com/websocket")
        ws.event.open = {
            print("opened")
        }
        ws.event.close = { code, reason, clean in
            print("close")
        }
        ws.event.error = { error in
            print("error \(error)")
        }

I am getting "The operation couldn’t be completed. (SwiftWebSocket.WebSocketError error 4.)"
