### ISSUE TITLE
Building for watchOS2 beta6

### ISSUE THREAD

**Issue by lesyk** [tidwall/SwiftWebSocket#9]
I manually added the files and getting:
WebSocket.swift:622:26: '[String]' does not have a member named 'joinWithSeparator'

**Comment by tidwall** [comment]
This error is related to a recent code update. `joinWithSeparator` is a function in the latest Xcode 7 Beta 6. Are you running this version of Xcode?

**Comment by lesyk** [comment]
My fault, mixed 5 and 6.
As I understand 

```
";".join(subProtocols)
```

will fix it?

**Comment by tidwall** [comment]
Yes. That will work for beta 5.
